/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { GuestAttendanceService } from "../guestAttendance.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { GuestAttendanceCreateInput } from "./GuestAttendanceCreateInput";
import { GuestAttendance } from "./GuestAttendance";
import { GuestAttendanceFindManyArgs } from "./GuestAttendanceFindManyArgs";
import { GuestAttendanceWhereUniqueInput } from "./GuestAttendanceWhereUniqueInput";
import { GuestAttendanceUpdateInput } from "./GuestAttendanceUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class GuestAttendanceControllerBase {
  constructor(
    protected readonly service: GuestAttendanceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: GuestAttendance })
  @nestAccessControl.UseRoles({
    resource: "GuestAttendance",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createGuestAttendance(
    @common.Body() data: GuestAttendanceCreateInput
  ): Promise<GuestAttendance> {
    return await this.service.createGuestAttendance({
      data: {
        ...data,

        guest: data.guest
          ? {
              connect: data.guest,
            }
          : undefined,
      },
      select: {
        createdAt: true,

        guest: {
          select: {
            id: true,
          },
        },

        id: true,
        isPresent: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [GuestAttendance] })
  @ApiNestedQuery(GuestAttendanceFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "GuestAttendance",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async guestAttendances(
    @common.Req() request: Request
  ): Promise<GuestAttendance[]> {
    const args = plainToClass(GuestAttendanceFindManyArgs, request.query);
    return this.service.guestAttendances({
      ...args,
      select: {
        createdAt: true,

        guest: {
          select: {
            id: true,
          },
        },

        id: true,
        isPresent: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: GuestAttendance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GuestAttendance",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async guestAttendance(
    @common.Param() params: GuestAttendanceWhereUniqueInput
  ): Promise<GuestAttendance | null> {
    const result = await this.service.guestAttendance({
      where: params,
      select: {
        createdAt: true,

        guest: {
          select: {
            id: true,
          },
        },

        id: true,
        isPresent: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: GuestAttendance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GuestAttendance",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateGuestAttendance(
    @common.Param() params: GuestAttendanceWhereUniqueInput,
    @common.Body() data: GuestAttendanceUpdateInput
  ): Promise<GuestAttendance | null> {
    try {
      return await this.service.updateGuestAttendance({
        where: params,
        data: {
          ...data,

          guest: data.guest
            ? {
                connect: data.guest,
              }
            : undefined,
        },
        select: {
          createdAt: true,

          guest: {
            select: {
              id: true,
            },
          },

          id: true,
          isPresent: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: GuestAttendance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GuestAttendance",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteGuestAttendance(
    @common.Param() params: GuestAttendanceWhereUniqueInput
  ): Promise<GuestAttendance | null> {
    try {
      return await this.service.deleteGuestAttendance({
        where: params,
        select: {
          createdAt: true,

          guest: {
            select: {
              id: true,
            },
          },

          id: true,
          isPresent: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
